version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12.x
    commands:
      - npm install

  build:
    commands:
      - npm run build:prod

artifacts:
  files:
    - "**/*"
  base-directory: "dist*"
  discard-paths: yes
